### ISSUE TITLE
Observer not triggered

### ISSUE THREAD

**Issue by Robert-M-Muench** [lempiji/rx#18]
Since we can't send PM and I don't have any email I try it via an issue:
Platform: win-10

I want to observe all WM_* messages that flow to a window-proc. So I created some global (I know bad style but for a playground OK) stuff but the observer is never triggered.

```
// windows message that should go to the observer
class winMsg {
  HWND    hwnd;
  UINT    message;
  WPARAM  wParam;
  LPARAM  lParam;

  this(HWND chwnd, UINT cmessage, WPARAM cwParam, LPARAM clParam){
    hwnd    = chwnd;
    message = cmessage;
    wParam  = cwParam;
    lParam  = clParam;
  }
  this(){}
}

// oberservable of windows messages
class osStream {
  static winMsg currentMsg;
  static SubjectObject!winMsg WMStream;
  
  static this() {
    WMStream = new SubjectObject!winMsg;
  }
}
```

During app initialization I created a filtered stream of `osStream.WMStream`and want to call an init function. 

```
  // if we receive a WM_CREATE, we initalize the app
  auto initStream = osStream.WMStream.filter!(n => n.message == WM_CREATE).doSubscribe((winMsg msg) {appInit();});
 ```
and appInit() is jsut a simple dummy function:

```
void appInit(){
  OutputDebugString("App started!");
}
```
And this function never gets called.

Any idea what I'm doing wrong?

**Comment by lempiji** [comment]
like this?

```d
while(PeekMessage(&msg))
{
    import std.range: put;
    put(osStram.WMStream, msg);
}
```

**Comment by Robert-M-Muench** [comment]
The problem is the line where doSubscribe() is called and it has to do with scoping, which I don't understand.

My idea is, I have a global observable (a message stream) I can subscribe to from different places in my application. Like: 

`osStream.doSubscribe(...)`

But as soon as this call gets out of scope, it seems to be destroyed and hence the code is not run. What I would like to do is, to keep the code active.

How can this be done?

doSubscribe() returns a disposable, can this be used to unsubscribe from the observable?

**Comment by lempiji** [comment]
Yes.
The return value of doSubscribe(...) is a subscription and it is used to unsubscribe.
It is a usage that calls the dispose method when it becomes unnecessary or you want to stop it.

In view of memory leaks and life cycles, initStream.dispose() should be called after appInit().

**Comment by Robert-M-Muench** [comment]
If I don't take the return value the subscription would last forever? So, it is not automatically disposed if  it goes out of scope?

If appInit() could be called several times (for every new window or so) I have to keep the subscription and can't dispose it. So, need to track the subscriptions somehow differently. Right?

**Comment by lempiji** [comment]
Yes, you don't take the return value the subscription would last forever.
Normally, you only have to call dispose to unsubscribe.

If you do not solve it, I try to challenge a Win32 example as well:+1:

**Comment by Robert-M-Muench** [comment]
dispose: Ok, got it. Still not sure I understand all the different types and what these are for.

My code is already working. Maybe it would help a lot to add a couple of sentences to the classes and a couple of comments to the examples.

**Comment by lempiji** [comment]
That's good.
Continue the documentation. If there is anything else, please question with a new Issue.
