### ISSUE TITLE
CompositeObserver / several times the same observer

### ISSUE THREAD

**Issue by Robert-M-Muench** [lempiji/rx#32]
It seems that CompositeObserver accepts the same observer several times by appending it several times. When removing an observer, only the first instance found is removed (because of using .countUntil().

IMO this should be streamlined and made more consistent: Either avoid adding the same observer several times or when removing the observer remove all instances, not only the first one, by using .count() instead of .countUntil()

**Comment by lempiji** [comment]
I tried to look at the movement in some other libraries, but I did not find anything that would cancel all the observers in a single dispose.
I think that it is better to put it in CompositeDisposable if it is necessary to release it collectively.
